name: Secrets Validation

on:
  workflow_dispatch:
  schedule:
    # Check secrets weekly on Sundays at 3 AM UTC
    - cron: '0 3 * * 0'

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Azure Credentials
      run: |
        echo "Checking required secrets..."
        
        # Check if AZURE_CREDENTIALS secret exists
        if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
          echo "❌ AZURE_CREDENTIALS secret is missing"
          echo "Please add this secret to enable Azure deployments"
          MISSING_SECRETS=true
        else
          echo "✅ AZURE_CREDENTIALS secret is configured"
        fi
        
        # Check if AZURE_DB_CONNECTION_STRING exists
        if [ -z "${{ secrets.AZURE_DB_CONNECTION_STRING }}" ]; then
          echo "❌ AZURE_DB_CONNECTION_STRING secret is missing"
          echo "Please add this secret to enable database migrations"
          MISSING_SECRETS=true
        else
          echo "✅ AZURE_DB_CONNECTION_STRING secret is configured"
        fi
        
        # Check if JWT secrets exist
        if [ -z "${{ secrets.JWT_SECRET }}" ]; then
          echo "⚠️ JWT_SECRET secret is missing (optional)"
        else
          echo "✅ JWT_SECRET secret is configured"
        fi
        
        if [ -z "${{ secrets.JWT_ISSUER }}" ]; then
          echo "⚠️ JWT_ISSUER secret is missing (optional)"
        else
          echo "✅ JWT_ISSUER secret is configured"
        fi
        
        # Generate summary
        echo "## Secrets Status" >> $GITHUB_STEP_SUMMARY
        if [ "$MISSING_SECRETS" = "true" ]; then
          echo "❌ Some required secrets are missing" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Required Secrets:" >> $GITHUB_STEP_SUMMARY
          echo "- \`AZURE_CREDENTIALS\`: Azure service principal credentials" >> $GITHUB_STEP_SUMMARY
          echo "- \`AZURE_DB_CONNECTION_STRING\`: Database connection string" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Optional Secrets:" >> $GITHUB_STEP_SUMMARY
          echo "- \`JWT_SECRET\`: JWT signing key" >> $GITHUB_STEP_SUMMARY
          echo "- \`JWT_ISSUER\`: JWT issuer" >> $GITHUB_STEP_SUMMARY
          exit 1
        else
          echo "✅ All required secrets are configured" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Validate Secret Formats
      run: |
        echo "Validating secret formats..."
        
        # Check Azure credentials format (should be JSON)
        if [ -n "${{ secrets.AZURE_CREDENTIALS }}" ]; then
          echo '${{ secrets.AZURE_CREDENTIALS }}' | jq . > /dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "✅ AZURE_CREDENTIALS has valid JSON format"
          else
            echo "❌ AZURE_CREDENTIALS is not valid JSON"
            exit 1
          fi
        fi
        
        # Check connection string format
        if [ -n "${{ secrets.AZURE_DB_CONNECTION_STRING }}" ]; then
          if [[ "${{ secrets.AZURE_DB_CONNECTION_STRING }}" == *"Host="* ]] || [[ "${{ secrets.AZURE_DB_CONNECTION_STRING }}" == *"Server="* ]]; then
            echo "✅ AZURE_DB_CONNECTION_STRING appears to be a valid connection string"
          else
            echo "⚠️ AZURE_DB_CONNECTION_STRING format might be invalid"
          fi
        fi
